name: Pull request

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    name: Test
    #uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    uses: swift-android-sdk/github-workflows/.github/workflows/swift_package_test.yml@android-sleep-before-adb
    with:
      linux_exclude_swift_versions: '[{"swift_version": "5.8"}, {"swift_version": "5.9"}, {"swift_version": "5.10"}]'
      windows_exclude_swift_versions: '[{"swift_version": "5.9"}, {"swift_version": "5.10"}]'
      macos_exclude_xcode_versions: '[{"xcode_version": "26.0"}]'
      enable_macos_checks: true
      enable_wasm_sdk_build: true
      enable_android_sdk_build: true
      enable_android_sdk_checks: true

  embedded-swift:
    name: Build with Embedded Swift
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.2
    with:
      enable_linux_checks: false
      enable_macos_checks: false
      enable_windows_checks: false
      enable_wasm_sdk_build: false
      enable_embedded_wasm_sdk_build: true
      swift_flags: --target Collections

  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@0.0.2
    with:
      license_header_check_project_name: "Swift.org"
      # https://github.com/apple/swift-collections/issues/428
      python_lint_check_enabled: false
      # https://github.com/apple/swift-collections/issues/429
      docs_check_enabled: false
      # https://github.com/apple/swift-collections/issues/430
      shell_check_enabled: false
      # https://github.com/apple/swift-collections/issues/431
      format_check_enabled: false
      # https://github.com/apple/swift-collections/issues/434
      license_header_check_enabled: false
      # https://github.com/apple/swift-collections/issues/435
      api_breakage_check_enabled: false
